apiVersion: batch/v1
kind: Job
metadata:
  annotations: &id001
    eidf/email: aryo.gema@ed.ac.uk
    eidf/user: aryogema
    groups: eidf106 eidf-gateway-login eidf106-login-login
    home: /home/eidf106/eidf106/aryogema
    login_user: aryogema
    shell: /bin/bash
  labels: &id002
    eidf/user: aryogema
    kueue.x-k8s.io/queue-name: eidf106ns-user-queue
    kueue.x-k8s.io/priority-class: batch-workload-priority
  generateName: aryo-decore-
  namespace: eidf106ns
spec:
  backoffLimit: 4
  template:
    metadata:
      annotations: *id001
      labels: *id002
    spec:
      containers:
      - args:
        - apt update && apt install nano byobu htop nvtop jq rsync sqlite3 libsqlite3-dev -y && curl -LsSf https://astral.sh/uv/install.sh | sh && export PATH="$HOME/.local/bin:$PATH" && git clone https://$GIT_TOKEN@github.com/aryopg/locos_eval.git && cd locos_eval && while true; do sleep 60; done;
        command:
        - /bin/bash
        - -c
        - --
        env:
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: aryo-secrets
              key: aryo-git-token
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: aryo-secrets
              key: aryo-wandb-api-key
        - name: WANDB_ENTITY
          valueFrom:
            secretKeyRef:
              name: aryo-secrets
              key: aryo-wandb-entity
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: aryo-secrets
              key: aryo-hf-token
        - name: HF_USERNAME
          valueFrom:
            secretKeyRef:
              name: aryo-secrets
              key: aryo-hf-username
        image: runpod/pytorch:1.0.3-cu1281-torch291-ubuntu2404
        imagePullPolicy: Always
        name: aryo-decore
        resources:
          limits:
            cpu: '32'
            memory: 256Gi
            nvidia.com/gpu: 4
          requests:
            cpu: '32'
            memory: 256Gi
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3
      restartPolicy: Never
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 64Gi
        name: dshm